"""Add gender column to doctor table

Revision ID: caad4086c92e
Revises: e212cc27f64f
Create Date: 2025-12-02 11:34:20.446848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caad4086c92e'
down_revision: Union[str, Sequence[str], None] = 'e212cc27f64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('gender', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'gender')
    # ### end Alembic commands ###
